import { Question } from './types';

export const questions: Question[] = [
  // Q1: 페르소나 식별용 (점수에 기여하지 않음)
  {
    id: 'q1',
    text: '지금 나의 상황을 가장 잘 나타내는 건?',
    contributeToScore: false,
    options: [
      {
        id: 'q1_a',
        text: '취준생 — 첫 직장·인턴·계약직 준비 중',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q1_b',
        text: '재학생 — 진로 탐색·학점 병행 중',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q1_c',
        text: '직무 전환 준비 중',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q1_d',
        text: '비IT 직장인 — 업무 역량·AI 리터러시 강화',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q1_e',
        text: 'IT·개발 직장인 — 실무 증명·이직 준비',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q1_f',
        text: '아직 정해지지 않음 — 방향부터 잡기',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
  // Q2: 도구 사용 (점수에 기여)
  {
    id: 'q2',
    text: '지난 1개월 동안 컴퓨터로 가장 많이 쓴 도구는?',
    contributeToScore: true,
    options: [
      {
        id: 'q2_a',
        text: 'Excel · Google Sheets — 숫자·표 정리가 많다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 3,
          Security: 0,
          M365: 0,
          PowerPlatform: 2,
          Copilot: 0,
        },
      },
      {
        id: 'q2_b',
        text: 'Word · 노션 · Google Docs — 문서·보고서·과제',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 2,
          PowerPlatform: 0,
          Copilot: 2,
        },
      },
      {
        id: 'q2_c',
        text: 'Teams · Slack · 카톡 — 회의·협업·커뮤니케이션',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 3,
          PowerPlatform: 0,
          Copilot: 2,
        },
      },
      {
        id: 'q2_d',
        text: 'ChatGPT · Copilot · Claude — AI 도구가 손에 붙음',
        weight: {
          AI: 3,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 2,
        },
      },
      {
        id: 'q2_e',
        text: 'VSCode · GitHub · Python · SQL — 코드·데이터 작업',
        weight: {
          AI: 2,
          Cloud: 3,
          Data: 2,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q2_f',
        text: 'Figma · Canva · 콘텐츠 툴 — 디자인·콘텐츠 제작',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 1,
          Copilot: 1,
        },
      },
      {
        id: 'q2_g',
        text: '관리 콘솔 · 로그 · 보안 도구 (학교/회사에서 접함)',
        weight: {
          AI: 0,
          Cloud: 1,
          Data: 0,
          Security: 3,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
  // Q3: 자격증 동기 (점수에 기여 + 타이브레이커)
  {
    id: 'q3',
    text: '자격증을 알아보기 시작한 결정적인 계기는?',
    contributeToScore: true,
    options: [
      {
        id: 'q3_a',
        text: '서류·자소서·이력서에 "이걸 할 줄 안다"는 한 줄이 필요하다',
        weight: {
          AI: 0.5,
          Cloud: 0.5,
          Data: 0.5,
          Security: 0.5,
          M365: 0.5,
          PowerPlatform: 0.5,
          Copilot: 0.5,
        },
      },
      {
        id: 'q3_b',
        text: 'AI 시대에 나만 뒤처지는 느낌이 든다',
        weight: {
          AI: 3,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 2,
        },
      },
      {
        id: 'q3_c',
        text: '비전공·문과 출신이라 IT·데이터 영역 진입이 막연하다',
        weight: {
          AI: 1,
          Cloud: 0,
          Data: 2,
          Security: 0,
          M365: 0,
          PowerPlatform: 2,
          Copilot: 0,
        },
      },
      {
        id: 'q3_d',
        text: '엑셀·반복 업무의 한계를 느끼고 더 의미 있게 일하고 싶다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 3,
          Security: 0,
          M365: 0,
          PowerPlatform: 2,
          Copilot: 0,
        },
      },
      {
        id: 'q3_e',
        text: '주변(동기·친구·동료)이 뭔가 시작해서 조급해졌다',
        weight: {
          AI: 0.5,
          Cloud: 0.5,
          Data: 0.5,
          Security: 0.5,
          M365: 0.5,
          PowerPlatform: 0.5,
          Copilot: 0.5,
        },
      },
      {
        id: 'q3_f',
        text: '학교·회사·업계에 Copilot·AI·클라우드가 들어오는데 겉돈다',
        weight: {
          AI: 2,
          Cloud: 1,
          Data: 0,
          Security: 0,
          M365: 1,
          PowerPlatform: 0,
          Copilot: 2,
        },
      },
      {
        id: 'q3_g',
        text: '데이터·보안·클라우드가 유망하다는데 구체 방향을 못 잡겠다',
        weight: {
          AI: 0,
          Cloud: 1,
          Data: 1,
          Security: 1,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
  // Q4: 코딩 역량 (점수에 기여, 음수 가중치 포함)
  {
    id: 'q4',
    text: '코딩·스크립트에 대한 솔직한 내 입장은?',
    contributeToScore: true,
    options: [
      {
        id: 'q4_a',
        text: '최대한 피하고 싶어요',
        weight: {
          AI: 0,
          Cloud: -2,  // 음수 가중치
          Data: 0,
          Security: -1,  // 음수 가중치
          M365: 2,
          PowerPlatform: 3,
          Copilot: 2,
        },
      },
      {
        id: 'q4_b',
        text: '배울 마음은 있지만 두려워요',
        weight: {
          AI: 1,
          Cloud: 0,
          Data: 1,
          Security: 0,
          M365: 0,
          PowerPlatform: 1,
          Copilot: 0,
        },
      },
      {
        id: 'q4_c',
        text: 'Python·SQL 기본은 해요',
        weight: {
          AI: 2,
          Cloud: 1,
          Data: 3,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q4_d',
        text: '실제 프로젝트·업무에서 써요',
        weight: {
          AI: 3,
          Cloud: 3,
          Data: 0,
          Security: 2,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
  // Q5: 목표 경험 (점수에 기여)
  {
    id: 'q5',
    text: '1~2년 안에 내가 가장 얻고 싶은 경험은?',
    contributeToScore: true,
    options: [
      {
        id: 'q5_a',
        text: 'AI·Copilot으로 업무·학업·과제를 바꿔본 경험',
        weight: {
          AI: 3,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 3,
        },
      },
      {
        id: 'q5_b',
        text: '데이터를 분석해 설득력 있는 결과를 만든 경험',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 3,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q5_c',
        text: '클라우드로 서비스·인프라를 다뤄본 경험',
        weight: {
          AI: 0,
          Cloud: 3,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q5_d',
        text: '보안·개인정보 이슈를 이해·대응해본 경험',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 3,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q5_e',
        text: '반복 업무·프로세스를 자동화해본 경험 (코딩 최소)',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 3,
          Copilot: 1,
        },
      },
      {
        id: 'q5_f',
        text: 'M365·Teams·Copilot을 조직 단위로 다뤄본 경험',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 3,
          PowerPlatform: 0,
          Copilot: 1,
        },
      },
      {
        id: 'q5_g',
        text: '아직 고르기 어려움 — 기본기부터 단단히',
        weight: {
          AI: 1,
          Cloud: 1,
          Data: 1,
          Security: 1,
          M365: 1,
          PowerPlatform: 1,
          Copilot: 1,
        },
      },
    ],
  },
  // Q6: 시간 투자 (점수에 기여하지 않음, 메타데이터용)
  {
    id: 'q6',
    text: '자격증에 투자할 수 있는 현실적인 시간은?',
    contributeToScore: false,
    options: [
      {
        id: 'q6_a',
        text: '2~3주 — 빠르게 하나 따고 싶다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q6_b',
        text: '1~2개월 — 여유 있게 준비',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q6_c',
        text: '3개월 이상 — 제대로 공부',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q6_d',
        text: '상황 따라 유동적',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
  // Q7: 장벽 (점수에 기여하지 않음, 콘텐츠 훅용)
  {
    id: 'q7',
    text: '자격증 공부를 시작하려 할 때 가장 걸리는 건?',
    contributeToScore: false,
    options: [
      {
        id: 'q7_a',
        text: '비전공 용어가 외국어처럼 느껴진다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_b',
        text: '응시료·교재비가 부담된다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_c',
        text: '실제 취업·업무에 써먹히는지 확신이 안 선다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_d',
        text: '자소서·이력서에 어떻게 녹여야 할지 모르겠다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_e',
        text: '시간 내기가 벅차다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_f',
        text: '혼자 하면 동기가 안 생긴다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
      {
        id: 'q7_g',
        text: '어디서부터 시작해야 할지 모르겠다',
        weight: {
          AI: 0,
          Cloud: 0,
          Data: 0,
          Security: 0,
          M365: 0,
          PowerPlatform: 0,
          Copilot: 0,
        },
      },
    ],
  },
];
